name = "Slurm"
uuid = "ca04f62e-b8d1-11e9-21e4-5fd4efd763a3"
authors = ["Qi Zhang <singularitti@outlook.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
